[pytest]
testpaths = tests

markers =
    api: API tests
    ui: UI tests
    smoke: smoke tests
    regression: regression tests

addopts = -v --tb=short

[pytest]
addopts = --alluredir=reports/allure-results